version: '3.3'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'LittleLemon'
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - '3307:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
